name: Node CI

on:
    push:
        branches:
            - vertex-ai

    pull_request:
        branches:
            - '*'

permissions:
    contents: read

jobs:
    build:
        strategy:
            matrix:
                platform: [ubuntu-latest]
                node-version: [18.15.0]
        runs-on: ${{ matrix.platform }}
        env:
            PUPPETEER_SKIP_DOWNLOAD: true
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: 9.0.4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  check-latest: false
                  cache: 'pnpm'

            - run: npm i -g pnpm

            - run: pnpm install

            - run: ./node_modules/.bin/cypress install

            - run: pnpm lint

            - run: pnpm build
            - name: Docker Login
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            # Build and Push Docker Image
            - name: Build and Push Docker Image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: asadul/flowise:1.0.0
